name: Testing workflow

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install black for file style check"
        run: pip install black
      - name: "Run black"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install pytest and coverage"
        run: pip install pytest coverage
      - name: "Run test"
        run: python -m pytest
      - name: "Run coverage"
        run: python -m coverage
#    needs: style
#    runs-on: ubuntu-latest
#    env:
#      PROJECT_NAME: "Automation Lecture"
#    steps:
#      - name: "Run build phase"
#        run: echo "Building project $PROJECT_NAME"
#  test:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.8'
#      - name: "Run unittest"
#        run: python -m unittest